Find and Replace
use regex::Regex::replace_all to find and replace text.

% echo "Hello, world" > test.txt

% cargo run -q "world" "Rust" test.txt test-modified.txt
Arguments { target: "world", replacement: "Rust", filename: "test.txt", output: "test-modified.txt" }

% cat test-modified.txt
Hello, Rust

% cargo run -q "[[a-z]" "Rust" test.txt test-modified.txt
Arguments { target: "[[a-z]", replacement: "Rust", filename: "test.txt", output: "test-modified.txt" }
Error: failed to replace text: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    [[a-z]
    ^
error: unclosed character class
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)

% cargo run -q "[[a-z]]" "Rust" test.txt test-modified.txt
Arguments { target: "[[a-z]]", replacement: "Rust", filename: "test.txt", output: "test-modified.txt" }

% cat test-modified.txt
HRustRustRustRust, RustRustRustRustRust

% cargo run -q "[[a-z]]" "0" test.txt test-modified.txt
Arguments { target: "[[a-z]]", replacement: "0", filename: "test.txt", output: "test-modified.txt" }

% cat test-modified.txt
H0000, 00000